application: princetondinkylink
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: dinkylink.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

# application: scraper-cron
# version: 1
# runtime: python27
# api_version: 1

# handlers:
# - url: /scrape
